name: Docker Dual Publish

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches: 
      - main-enterprise
    tags:
      - 'v*.*.*'
  pull_request:
    branches: 
      - main-enterprise

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          # Need to revise this... 
          ## Always publish to GHCR
          ## Release publish to Docker Hub
          GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/dual-publish
          DOCKER_IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/dual-publish

          VERSION=edge

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi

          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          fi

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # only publish PRs to GHCR
            PR_NUMBER=$(echo ${{ github.ref }} | sed -r 's/^refs\/pull\/([0-9]+)\/merge/\1/')
            VERSION=pr-$PR_NUMBER
            TAGS="${GHCR_IMAGE}:${VERSION},${GHCR_IMAGE}:${GITHUB_SHA}"
          else
            TAGS="${GHCR_IMAGE}:${VERSION},${GHCR_IMAGE}:${GITHUB_SHA},${DOCKER_IMAGE}:${VERSION}"
            if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
              TAGS="$TAGS,${GHCR_IMAGE}:latest,${DOCKER_IMAGE}:latest"
            fi
          fi

          echo ::set-output name=tags::${TAGS}

          # lowercase the branch name
          BRANCH=$(echo ${GITHUB_REF##*/} | tr '[A-Z]' '[a-z]')

          LABELS="org.opencontainers.image.revision=$GITHUB_SHA"
          LABELS="$LABELS,org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          LABELS="$LABELS,org.opencontainers.image.version=$VERSION"
          LABELS="$LABELS,com.github.repo.branch=$BRANCH"
          LABELS="$LABELS,com.github.repo.dockerfile=Dockerfile"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_NUMBER=$(echo ${{ github.ref }} | sed -r 's/^refs\/pull\/([0-9]+)\/merge/\1/')
            LABELS="$LABELS,com.github.repo.pr=$PR_NUMBER"
          fi
          echo ::set-output name=labels::${LABELS}

          BUILD_ARGS="BRANCH=$BRANCH"
          echo ::set-output name=args::${BUILD_ARGS}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GHCR
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          build-args: ${{ steps.prep.outputs.args }}
          labels: ${{ steps.prep.outputs.labels }}
