name: Docker Dual Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches: 
      - main-enterprise
    tags:
      - 'v*.*.*'
  pull_request:
    branches: 
      - main-enterprise

env:
  # TODO: Change variable to your image's name.
  FIRST_IMAGE_NAME: ${{ github.repository_owner }}/simple-docker
  # TODO: Set registry. Use docker.io for DockerHub
  FIRST_REGISTRY: ghcr.io
  SECOND_IMAGE_NAME: ${{ github.repository_owner }}/simple-docker
  # TODO: Set registry. Use docker.io for DockerHub
  SECOND_REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: president-business-corp/simple-docker/metadata@trunk
        id: first
        with:
          image-name: ${{ env.FIRST_IMAGE_NAME }}
          registry: ${{ env.FIRST_REGISTRY }}

      - uses: president-business-corp/simple-docker/metadata@trunk
        id: second
        with:
          image-name: ${{ env.SECOND_IMAGE_NAME }}
          registry: ${{ env.SECOND_REGISTRY }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to GHCR
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ${{ steps.first.outputs.file }}
          push: true
          tags: ${{ steps.first.outputs.tags }},${{ steps.second.outputs.tags }}
          build-args: ${{ steps.first.outputs.args }},${{ steps.second.outputs.args }}
          labels: ${{ steps.first.outputs.labels }},${{ steps.second.outputs.labels }}
